version: "3.7"

services:
  database:
    image: postgres
    container_name: database_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/data/postgres